### PR TITLE
Support TM_MARKDOWN_FILTER

### PR DESCRIPTION
**Pull request by noniq**
See discussion in http://lists.macromates.com/textmate/2016-July/039720.html

Depends on https://github.com/textmate/markdown.tmbundle/pull/39, of course.

### CODE REVIEW

**Comment by sorbits** [comment]
I am thinking it might make sense to name the variable `TM_MARKDOWN_PRE_FILTER` then we can also have `TM_MARKDOWN_POST_FILTER` (which could replace the current `TM_SMARTYPANTS`, which I wouldn’t mind seeing go).

Objections?

/cc @infininight

**Comment by sorbits** [comment]
Might also be possible to do the `TM_MARKDOWN_MATHJAX` as a filter, possibly this should just be enabled by default?

**Comment by noniq** [comment]
No objections at all, sounds very reasonable. Will work on it later today!

**Comment by noniq** [comment]
Replacing the support for `TM_SMARTYPANTS` with `TM_MARKDOWN_POST_FILTER` has two minor issues:
 * The option `:no_smartypants` will no longer work (not sure if it actually used anywhere besides the tests, though).
 * Until now, using Smartypants was the default. So I suppose `TM_MARKDOWN_POST_FILTER` should include Smartypants per default. But where should this be set (so that it is still customizable)?

**Comment by sorbits** [comment]
This is my personal preference, but I would not mind seeing default “SmartyPants” support be dropped.

Se we just have the pre-filter, markdown processor, and post-filter. Some of the markdown processors have some form of smart typography built-in already.

**Comment by noniq** [comment]
Should be done!

**Comment by noniq** [comment]
Implementing MathJax support via `TM_MARKDOWN_FILTER_POST` should be possible, too. Maybe a separate “extension bundle” (like my “Markdown (Front Matter)“ bundle) would be a good fit. Should I give it a try?

**Comment by sorbits** [comment]
Merged as 68fed7b...ea9802f, thanks!

I also removed the actual `SmartyPants.pl` file since nothing (that I am aware of) should use this.

I think it makes sense to have _Markdown (MathJax)_ as an extension bundle, please go ahead on this.

**Pull request closed without merging**
